### ISSUE TITLE
Cocoapods Support?

### ISSUE THREAD

**Issue by ghost** [Boerworz/Gagat#1]

**Comment by Boerworz** [comment]
Hey codingalex! I considered adding support for CocoaPods before releasing Gagat, but ultimately decided against it. I'm personally not a big fan of CocoaPods, mostly because I don't really understand everything it does to a project. I prefer the simplicity both in using and adding support for Carthage 🙂 Anyway, if more people show an interest in CocoaPods support in the future, I'll reconsider my decision.

**Comment by natanrolnik** [comment]
+1

I understand that some developers prefer one dependency manager over another, and that's totally fine 😊
But I believe that good libraries/components should be "dependency-manager-agnostic" in my opinion. For example, if someone has a project that heavily depends on CocoaPods, wouldn't be the best to add Carthage just for one dependency.

Do you recommend adding it manually, @Boerworz?

**Comment by Boerworz** [comment]
Hi @natanrolnik! Thank you for your input 🙂 Right now I recommend adding Gagat to your project manually.
